services:
  osp-api-gateway:
    build:
      context: .
    container_name: osp-api-gateway
    environment:
      - TZ=America/Bogota
      - INFORMATION_SERVICE_URL=http://osp-information-ms:8001
      - RASPBERRYPI_SERVICE_URL=http://host.docker.internal:8081
      - AUTH_SERVICE_URL=http://osp-authentication-ms:8000
      - REDIS_URL=redis://redis-db:6379
    ports:
      - "8887:8887"
    depends_on:
      - osp-authentication-ms
      - osp-information-ms
      # - osp-raspberrypi-ms
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8887/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - osp-network-public
      - osp-network-priv

    restart: unless-stopped