name: osp-platform

volumes:
  redis_db:
  postgres_db:

networks:
  osp-network-public:
    driver: bridge
  osp-network-priv:
    driver: bridge

include:
  - path: osp-authentication-ms/docker-compose.yml
    project_directory: osp-authentication-ms/
  - path: osp-information_gestor-ms/docker-compose.yml
    project_directory: osp-information_gestor-ms/
  # - path: osp-raspberrypi-ms/docker-compose.yml
  #   project_directory: osp-raspberrypi-ms/
  - path: home/docker-compose.yml
    project_directory: home/
  - path: osp-nginx-proxy/docker-compose.yml
    project_directory: osp-nginx-proxy/
  - path: api-gateway-ms/docker-compose.yml
    project_directory: api-gateway-ms/
  - path: osp-frontend-web/docker-compose.yml
    project_directory: osp-frontend-web/
  # - path: osp-electron/docker-compose.yml
  #   project_directory: osp-electron/