services:
  osp-frontend-web:
    build:
      context: .
    ports:
      - "5173:5173"
    image: osp-frontend-web:dev
    env_file:
      - .env
    
    environment:
      - NODE_ENV=production
    networks:
      - osp-network-public
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s