services:
  # Raspberry Pi - Solo captura y detección
  osp-raspberrypi:
    build:
      context: ./raspberry-pi
      dockerfile: Dockerfile
    image: osp-raspberrypi
    container_name: osp-raspberrypi
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - PROCESSING_SERVER_HOST=osp-processing-ms
      - PROCESSING_SERVER_PORT=8081
      - DOCKER_CONTAINER=true
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    networks:
      osp-network:
        ipv4_address: 172.20.0.9
    expose:
      - "8080"
    depends_on:
      - osp-processing-ms
    # Sin volúmenes - todo es temporal

  # Servidor de procesamiento - Maneja almacenamiento y lógica de negocio
  osp-processing-ms:
    build:
      context: ./processing-server
      dockerfile: Dockerfile
    image: osp-processing-ms
    container_name: osp-processing-ms
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - RASPBERRY_PI_HOST=osp-raspberrypi
      - RASPBERRY_PI_PORT=8080
      - DOCKER_CONTAINER=true
    ports:
      - "8080:8080"  # Puerto para la interfaz web
      - "8081:8081"  # Puerto para recibir datos de la raspberry
    networks:
      osp-network:
        ipv4_address: 172.20.0.12
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Para acceso desde host
    # Sin volúmenes - almacenamiento temporal en /tmp

networks:
  osp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16