services:
  # Servidor de procesamiento
  processing-server:
    build:
      context: .
      dockerfile: Dockerfile.processing
    container_name: processing-server
    ports:
      - "8080:8080"
    volumes:
      - ./events:/app/events
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - security-network
    restart: unless-stopped

  # Raspberry Pi 1 simulada
  pi1:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: pi1
    ports:
      - "8081:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_SERVER_HOSTNAME=http://processing-server:8080
      - PI_ID=pi1
    networks:
      - security-network
    depends_on:
      - processing-server
    restart: unless-stopped

  # Raspberry Pi 2 simulada
  pi2:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: pi2
    ports:
      - "8082:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_SERVER_HOSTNAME=http://processing-server:8080
      - PI_ID=pi2
    networks:
      - security-network
    depends_on:
      - processing-server
    restart: unless-stopped

networks:
  security-network:
    driver: bridge

volumes:
  events:
  logs: