services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - osp-network-public
    depends_on:
      - osp-api-gateway
      - osp-frontend-web
    restart: unless-stopped