services:
  osp-nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: osp-nginx-proxy:latest
    container_name: osp-nginx-proxy
    ports:
      - "80:80"
    networks:
      - osp-network-public
    depends_on:
      - osp-api-gateway
      - osp-frontend-web
    restart: unless-stopped