services:
  osp-authentication-ms:
    build:
      context: .
      dockerfile: Dockerfile
    image: osp-authentication-ms:dev
    container_name: osp-authentication-ms
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - osp-network-priv

  postgres-db:
    image: postgres:13-alpine
    container_name: postgres-db
    env_file: .env
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: postgres -c listen_addresses='*'
    networks:
      - osp-network-priv

volumes:
  postgres_db: