services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    # Para Raspberry Pi (si es necesario):
    # platform: linux/arm/v7

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # Configuración adicional para PostgreSQL
    environment:
      POSTGRES_USER : auth_user
      POSTGRES_PASSWORD : abc123
      POSTGRES_DB : auth_db
    command: postgres -c listen_addresses='*'

volumes:
  postgres_data: