services:
  osp-information-ms:
    build:
      context: .
    container_name: osp-information-ms
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - TZ=America/Bogota
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    depends_on:
      - redis-db
    networks:
      - osp-network-priv
      - osp-network-public

  redis-db:
    image: redis:latest
    container_name: redis-db
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
    volumes:
      - redis_db:/data
    command: redis-server --save 3600 1 --maxmemory 500mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - osp-network-priv

volumes:
  redis_db: