version: '3.8'

services:
  security-server:
    build: .
    container_name: security-server
    hostname: security-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./events:/app/events
      - ./logs:/app/logs
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=INFO
    command: >
      python security_server.py 
      --host ${HOST:-0.0.0.0} 
      --port ${PORT:-8080}
      --log-level ${LOG_LEVEL:-INFO}
    networks:
      - security-network

networks:
  security-network:
    driver: bridge
    name: security-network