services:
  osp-home-ms:
    build: .
    image: osp-home-ms
    container_name: security-server
    ports:
      - "8080:8080"
      - "9999:9999"
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - HOST=0.0.0.0
      - PORT=8080
      - ALLOWED_HOSTS=overwatch-sentinel-platform.local
    volumes:
      - ./events:/app/events
      - ./logs:/app/logs
    command: python security_server.py --host ${HOST:-0.0.0.0} --port ${PORT:-8080} --allowed-hosts ${ALLOWED_HOSTS}